# Generated by Django 5.1.4 on 2024-12-16 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name to categorize posts.', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'Postify_tag',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the post (max 200 characters).', max_length=50, verbose_name='Title')),
                ('content', models.TextField(help_text='The main content of the post. Use rich text for full details.', max_length=200, verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the post was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the post was last updated.')),
                ('category', models.CharField(choices=[('BLOG', 'Blog'), ('NEWS', 'News'), ('REVIEW', 'Review'), ('TUTORIAL', 'Tutorial')], default='BLOG', help_text='Category of the post (e.g., Blog, News).', max_length=50, verbose_name='Category')),
                ('is_published', models.BooleanField(default=True, help_text='Flag indicating whether the post is published.', verbose_name='Publication Date')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Rating of the post (e.g., a scale from 0 to 5).', max_digits=3, verbose_name='Rating')),
                ('website', models.URLField(blank=True, help_text='An external link related to the post.', null=True, verbose_name='Website')),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata related to the post (e.g., JSON structure).', null=True, verbose_name='Metadata')),
                ('author', models.ForeignKey(help_text='The author of this post (related to User model).', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags associated with this post (e.g., technology, lifestyle).', to='posts.tag')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'Postify_post',
                'ordering': ['-created_at'],
            },
        ),
    ]
