# Generated by Django 5.1.4 on 2024-12-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this post (e.g., #Blog, #lifestyle).', to='posts.tag'),
        ),
    ]
