# Generated by Django 5.1.4 on 2024-12-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, help_text='Tag name to categorize posts.', max_length=50, null=True, unique=True),
        ),
    ]
