# Generated by Django 5.1.4 on 2024-12-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('BLOG', 'Blog'), ('NEWS', 'News'), ('REVIEW', 'Review'), ('TUTORIAL', 'Tutorial')], default='BLOG', help_text='Category of the post (e.g., Blog, News).', max_length=50, null=True, verbose_name='Category'),
        ),
    ]
